
# Fichero para CI con Travis

# Indica el lenguaje a usar
language: java

# Especifica la version de jdk
jdk:
    - openjdk8

# Especifica que se va a usar docker
#services:
#    - docker

# Especifica el SO y la distribución a usar
arch: amd64
os: linux
dist: xenial

# Descarga la imagen y la ejecuta
#before_install:
#    - docker pull rauldpm/inmobiliv
#    - docker run -t -v `pwd`:/test rauldpm/inmobiliv

# Ejecuta el test
script:
    - gradle test