

# Especifica el SO y la distribución a usar
arch: amd64
os: linux
dist: xenial

# Indica el lenguaje a usar
language: java

# Especifica que se va a usar docker
services:
    - docker

# Descarga la imagen y la ejecuta
script:
    - docker build -t rauldpm/inmobiliv .
    - docker run -t -v `pwd`:/test rauldpm/inmobiliv 
