
# Fichero para CI con Travis

# Especifica el SO y la distribución a usar
arch: amd64
os: linux
dist: xenial

# Indica el lenguaje a usar
language: java

# Especifica la version de jdk
jdk:
    - openjdk8

# Especifica que se va a usar docker
services:
    - docker

# Descarga la imagen y la ejecuta
script:
    - docker pull rauldpm/inmobiliv
    - docker run -t -v `pwd`:/test rauldpm/inmobiliv

    