
# Fichero configuracion Circle-CI

version: 2.1

# Representa la lista de trabajos a ejecutarse
jobs:
    build:
        # Indica que es una maquina linux
        machine: true
        # Especifica las acciones a realizar
        steps:
            # Clona el repositorio en local
            - checkout
            # Comandos a ejecutar
            - run:
                # Usa ghcr.io
                command: |
                    docker pull ghcr.io/rauldpm/inmobiliv/inmobiliv-con:latest
                    docker run -t -v `pwd`:/test ghcr.io/rauldpm/inmobiliv/inmobiliv-con:latest