
version: 2.1

jobs:
    build:
        machine: true
        steps:
            - run:
                command: |
                    docker build -t rauldpm/inmobiliv .
                    docker run -t -v `pwd`:/test rauldpm/inmobiliv 