
# Fichero configuracion Circle-CI

version: 2.1

# Representa la lista de trabajos a ejecutarse
jobs:
    build:
        # Indica que es una maquina linux
        machine: true
        # Especifica las acciones a realizar
        steps:
            # Clona el repositorio en local
            - checkout
            # Comandos a ejecutar
            - run:
                command: |
                    docker build -t rauldpm/inmobiliv .
                    docker run -t -v `pwd`:/test rauldpm/inmobiliv 