
version: 2.1

jobs:
    build:
        steps:
            machine: true
            - run:
                command: |
                    docker build -t rauldpm/inmobiliv .
                    docker run -t -v `pwd`:/test rauldpm/inmobiliv 