
name: AWS

# Salta cuando hay un cambio en el fichero con la funcion serverless
on:
  push:
    paths:
      - 'app/src/main/kotlin/function_aws.kt'

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - 
        name: Checkout
        uses: actions/checkout@v2

      # Configura la accion con las credenciales de AWS
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Realiza el login con las credenciales
      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Despliega a AWS
      - 
        name: Deploy to AWS
        id: deploy
        run: "gradle deploy"
