name: Docker image 

on:
    push:
        paths:
            - 'Dockerfile'

jobs:
    push:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        
        steps:

            - 
              name: Checkout
              uses: actions/checkout@v2

            -
              name: Docker buildx
              uses: docker/setup-buildx-action@v1

            -
              name: LOGIN
              run: echo "${{ secrets.DOCKER_PASS }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin

            -
              name: BUILD and PUSH
              uses: docker/build-push-action@v2
              with:
                tags: ghcr.io/rauldpm/inmobiliv/inmobiliv-con:latest
                push: true
