
name: Deploy To Heroku

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'iv.yaml'
      - 'docs/**'
      - '.github/**'
      - 'README.md'


jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
        - uses: actions/checkout@v2

        - name: Testing
          run: gradle test 

        - name: Limpia ficheros test
          run: gradle clean

        - name: Build ficheros compilados
          run: gradle compileKotlin

        - name: Login Heroku
          env:
            HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          run: heroku container:login

        - name: Push image
          env:
            HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          run: heroku container:push web --recursive --app inmobiliv
        
        - name: Release image
          env:
            HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          run: heroku container:release web --app inmobiliv  