
# Este workflow sirve de ejemplo para un despliegue desde el plugin del taskrunner hacia Heroku
# El deploy actual se realiza en el workflow "heroku.yml" utilizando un contenedor

name: Deploy To Heroku

on:
  push:
    branches-ignore: # Ignora los eventos de la rama master
      - master
    paths-ignore:
      - 'iv.yaml'
      - 'docs/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
        - uses: actions/checkout@v2

        - name: Genera fichero Jar y comprueba test
          run: gradle build

        - name: Login
          env:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          run: heroku login

        - name: Prepara despliegue
          run: heroku plugins:install java

        - name: Deploy
          env:
            HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          run: gradle deployHeroku