
name: Deploy To Heroku

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'iv.yaml'
      - 'docs/**'
      - '.github/**'


jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
        - uses: actions/checkout@v2

        - name: Login
          env:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          run: heroku container:login

        - name: Push imagen
          run: heroku container:push web --recursive --app inmobiliv
        
        - name: Release imagen
          run: heroku container:release web --app inmobiliv  